### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.NodeServices.OutOfProcessNodeInstance' from assembly 'Microsoft.AspNetCore.NodeServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by harsimranb** [frankwallis/WebpackAspnetMiddleware#10]
I followed the setup in the ReadMe, except that I am using version 1 of this library: 
"Redouble.AspNet.Webpack": "1.0.0"

Additional information: Could not load type 'Microsoft.AspNetCore.NodeServices.OutOfProcessNodeInstance' from assembly 'Microsoft.AspNetCore.NodeServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Any ideas?

**Comment by frankwallis** [comment]
I have upgraded to the latest dependencies, please reopen if still an issue.
