### ISSUE TITLE
 Unable to locate Dependency System.Net.Sockets >= 4.1.0-rc2-23706

### ISSUE THREAD

**Issue by joshburgess** [frankwallis/WebpackAspnetMiddleware#3]
Hi, for DNXCore it seems that a web sockets dependency of the Redouble.AspNet.Webpack NuGet package is no longer available. It looks like the System.Net.Sockets package is now using a beta tag rather than an rc tag, and it fails to find the version it currently depends on. Is there any way we can get that dependency updated so that Redouble.AspNet.Webpack is once again usable?

**Comment by frankwallis** [comment]
Thank you for raising this - I just published 0.7.8 which should fix that dependency. Let me know if it doesn't work for any reason.

**Comment by joshburgess** [comment]
Thanks. Seems to not be an issue now. Will let you know how using it goes!

**Comment by frankwallis** [comment]
I am interested to know how you get on, I am aware that there may be an issue with Kestrel dropping the long-polling connection after a time. We have delayed our upgrade to ASP.NET 5 at work, so I'm not using this project at the moment, but my plan is to give it some more attention when rc2 is released.

**Comment by joshburgess** [comment]
I gave up for now. I was getting some sort of cryptic Kestrel error about a
directory not being found when trying navigate to the localhost. I'm not
really sure why. I'll try to get back to it later on to see if I can get it
working.
