### ISSUE TITLE
Is this project replaced with the one found in the Nodeservices itself ?

### ISSUE THREAD

**Issue by CedricDumont** [frankwallis/WebpackAspnetMiddleware#4]
here the functionality seem to be in Nodeservices package. 

https://github.com/aspnet/NodeServices/tree/master/src/Microsoft.AspNet.SpaServices/Webpack

just to be sure to use the correct package or asking : why this package?

**Comment by frankwallis** [comment]
I wrote this before the NodeServices one existed, functionally I think they are pretty similar, but I haven't actually tried the NodeServices project. These are the differences which I am aware of:

The main differences is that this project communicates directly with a running instance of webpack, whereas the NodeServices project starts a nodejs 'Connect' instance running webpack-dev-middleware, and proxies the HTTP requests to that.

I like to think that this project is more focused on achieving its one goal, but that is clearly a matter of opinion. I think it is well designed and it does have tests which is an important criteria for me when choosing open source projects. There is a potential issue related to Kestrel lacking proper support for Server-Sent Events, but I think will be resolved in rc2 at which point I intend to spend a bit more time on this project.

Hopefully this answers your question, if you have time I suggest you give them both a try and see which one works for you.
