### ISSUE TITLE
error starting project

### ISSUE THREAD

**Issue by lucamorelli** [frankwallis/WebpackAspnetMiddleware#5]
Hi, 
  I just created a new asp.net 5 rc 1 web api project and copied all the files in the new project. the bundle is created correcty and placed in the correct directory, but when I try to run it I have this exception

      Request starting HTTP/1.1 GET http://localhost:5000/webpack/main.bundle.js
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[3]
      Request finished in 0,0265ms 500
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.Exception: no such file or directory
         in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         in Redouble.AspNet.Webpack.NodeHost.<Invoke>d__15.MoveNext()
      --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
         in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         in Redouble.AspNet.Webpack.NodeHost.<Invoke>d__16`1.MoveNext()
      --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
         in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         in Redouble.AspNet.Webpack.WebpackService.<GetFile>d__7.MoveNext()
      --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
         in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
         in Redouble.AspNet.Webpack.DevServer.<Invoke>d__4.MoveNext()
      --- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
         in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         in Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__8.MoveNext()

Am I missing something?

**Comment by frankwallis** [comment]
Have you run ```npm install```? There are some JavaScript files which are needed as well..

**Comment by lucamorelli** [comment]
I think is all correct. I saved the package.json from inside vs and it restarted the restore.
This is what I see
![untitled2](https://cloud.githubusercontent.com/assets/127777/14792622/65112808-0b1b-11e6-9e54-87fdfa862c1f.png)

Anyway I'm going to delete the node_modules dire and rerun the install from cmd line to be sure

**Comment by frankwallis** [comment]
A couple more things to try:
- you should be able to run webpack from the command line with no errors
- what is the path of the root directory being served over http? - in the MVC project it is ```${ProjectDir}/wwwroot```. If the root served path is different in a WebAPI project then you will need to change ```wwwroot``` in ```webpack.config.js````

**Comment by lucamorelli** [comment]
the webpack compilation runs without errors and placed in the correct place.
the mvc configuration seems correct, and the view is correctly loaded, and find the bundle file.

**Comment by lucamorelli** [comment]
I added the sources and gives error in Line 164 of NodeHost.cs, at the end of the first Invoke. I think has some problems to connect to the node

**Comment by frankwallis** [comment]
I would not expect handler.js to end up in the bundle, but I would expect client.js to be included because of this entry in webpack.config.js:

```entry: ['webpack-aspnet-middleware/client', './index'],```

When the DevServer middleware is running it does not actually serve the bundled file in ```wwwroot```, it will serve the bundle which is created in memory by the running webpack instance.

It sounds like it may not be able to find the webpack.config.js file - by default it will look for it in ```IApplicationEnvironment.ApplicationBasePath``` and expect it to be called ```webpack.config.js``` as per [here](https://github.com/frankwallis/WebpackAspnetMiddleware/blob/master/Redouble.AspNet.Webpack/Services/WebpackService.cs#L41) and [here](https://github.com/frankwallis/WebpackAspnetMiddleware/blob/master/Redouble.AspNet.Webpack/Extensions.cs#L9)

If you are able to share some more of your configuration it may become clearer, but otherwise it's hard to know what the file is that it cannot find. I ought to add some debug logging to help diagnose these sort of issues.

In particular I am interested in knowing what you are setting ```publicPath``` to in the webpack config file and when you call ```AddWebpack``` as I know that can be a source of problems.

Does it look like it fails to start webpack properly at all, or does it seem as though it is just the HTTP request which fails to find the right output file from webpack?

**Comment by lucamorelli** [comment]
I think the webpack.config is correct: I don't understand very well what happens, but I suppose that when the asp.net app connect to net triggers the bundling of the webpack bundle. If so, the connection is working because after the start of the app I see in the console **? bundle is now valid**
If you like I can share the whole project

**Comment by frankwallis** [comment]
If you can share it I will certainly take a look. From what you said it sounds like:

a) the web application is requesting a file which is not being generated by webpack
b) the publicPath setting is incorrect

You should be able to get the path of the file which is not being found by looking in the 'network' tab of chrome dev tools and knowing that would be a help.

**Comment by lucamorelli** [comment]
you can download it at https://dl.dropboxusercontent.com/u/19486794/ReactHotReload.zip
In the solution I tried both with rc1-update1 and rc1-update2

In the console find this
http://localhost:5000/webpack/main.bundle.js 500 (Internal Server Error)

**Comment by frankwallis** [comment]
I gave it a try, but it is working for me. This is what I did:
- Extracted the Zip
- Ran ```dnu restore``` it failed with unable to install Redouble.AspNet.Webpack
- Updated the version of ```Redouble.AspNet.Webpack``` to be ```0.7.9``` in ```project.json```
- Ran ```dnu restore```
- Ran ```dnx web``` it failed with an error about ```root must be absolute path```
- Commented out ```ReloadOnChanged``` in ```Startup.cs``` - ```Configuration = builder.Build();//.ReloadOnChanged("appsettings.json");```
- Ran ```dnx web``` and it started ok

So I'm not sure exactly what is happening. I am running on a Mac using update1 with mono:

```
dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin          
       1.0.0-rc1-update1    coreclr x64          darwin          
  *    1.0.0-rc1-update1    mono                 linux/osx       default
       1.0.0-rc2-16357      mono                 linux/osx       
```

I will try it out on windows when I get a chance. but you may want to try deleting ```project.lock.json``` and running dnu restore again.

**Comment by frankwallis** [comment]
I'm closing this, I think the issue was that the project.lock.json contained a project reference instead of a package reference and this stopped working when the directories were moved.

Things have moved on since rc2 is now out with changes to project.json handling.
