### ISSUE TITLE
Cannot use this with Aspnet core rc2.

### ISSUE THREAD

**Issue by asadsahi** [frankwallis/WebpackAspnetMiddleware#6]
When adding this package in project.json and it is restored, in startup it errors when using:

  app.UseWebpackDevServer();                            // necessary
    app.UseWebpackHotReload(); 

![image](https://cloud.githubusercontent.com/assets/3470892/15358350/e1243c0e-1cfb-11e6-9a76-79586c183df7.png)

Not sure if this compatability issue.

**Comment by frankwallis** [comment]
Thanks for raising this, I've updated the project to use rc2 now, so this should be resolved in 0.8.1. If you are still seeing issues then please reopen.

**Comment by asadsahi** [comment]
Thanks @frankwallis . Will give it a try.
