### ISSUE TITLE
target framework 451

### ISSUE THREAD

**Issue by Alexander-Taran** [frankwallis/WebpackAspnetMiddleware#8]
there is an issue https://github.com/aspnet/JavaScriptServices/issues/103  @ aspnet/javascriptservices to target framework 451, please target this one as well, when they do.

**Comment by frankwallis** [comment]
Yes will do, my plan is to target netstandard@1.5 and 451 once aspnet/JavaScriptServices#90 is resolved.

**Comment by Alexander-Taran** [comment]
Good news, they merged PR (-:

**Comment by frankwallis** [comment]
Sorry for the slow response, I went away. I have published a new version 0.9.0 which targets netstandard1.3 and net451. It works ok on dnxcore, but I haven't tried it yet on .NET 451 so let me know if you have any issues there.
