### ISSUE TITLE
Benefits over WebpackDevMiddleware from JavascriptServices?

### ISSUE THREAD

**Issue by emzero** [frankwallis/WebpackAspnetMiddleware#9]
I'm using the react-redux template generated by the yeoman generator `aspnetcore-spa` and I've noticed they are using a WebpackDevMiddleware from [here](https://github.com/aspnet/JavaScriptServices/tree/master/src/Microsoft.AspNetCore.SpaServices/Webpack) which already includes the devserver with hot reload.

Not sure what are the benefits of using this one? Could you elaborate please?

Thanks

**Comment by frankwallis** [comment]
See https://github.com/frankwallis/WebpackAspnetMiddleware/issues/4. I don't really have anything to add to that, I'm happy to answer more questions though.
